"use client";

import { ArrowDown, ArrowUp, CalendarDays, Pencil, Plus, Trash2, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { normalizePlanItemInput, parsePlanResponse, type PlanItem, type PlanResponse } from "@/lib/plan";
import { clientErrorMessage } from "@/lib/client-error";
import { createRealtimeRefreshScheduler } from "@/lib/realtime-refresh";

type Props = { tripId: string; currentUserId: string; ownerId: string; isArchived: boolean; initialBoardNoteId?: string; initialPollId?: string };
const empty = { dayDate: "", startTime: "", title: "", description: "", locationText: "", boardNoteId: "", pollId: "" };
function message(code: unknown) { if (code === "TRIP_ARCHIVED") return "ทริปนี้ปิดแล้ว ไม่สามารถแก้ไขแผนได้"; if (code === "PLAN_FORBIDDEN") return "คุณไม่มีสิทธิ์ลบรายการนี้"; if (code === "VALIDATION_ERROR") return "กรอกข้อมูลแผนให้ครบถ้วน"; return "ดำเนินการไม่สำเร็จ กรุณาลองใหม่"; }

export function PlanWorkspace({ tripId, currentUserId, ownerId, isArchived, initialBoardNoteId, initialPollId }: Props) {
  const [data, setData] = useState<PlanResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [selectedDay, setSelectedDay] = useState(0); const [draft, setDraft] = useState(empty); const [editing, setEditing] = useState<PlanItem | null>(null); const [busy, setBusy] = useState(false); const requestRef = useRef<AbortController | null>(null);
  const load = useCallback(async () => { requestRef.current?.abort(); const controller = new AbortController(); requestRef.current = controller; try { const response = await fetch(`/api/trips/${tripId}/plan`, { cache: "no-store", signal: controller.signal }); const body: unknown = await response.json(); const parsed = parsePlanResponse(body); if (!response.ok || !parsed) throw new Error(message((body as { code?: unknown })?.code)); if (!controller.signal.aborted) { setData(parsed); setError(""); } } catch (cause) { if ((cause as Error).name !== "AbortError") setError(clientErrorMessage(cause, "โหลดแผนไม่สำเร็จ")); } finally { if (!controller.signal.aborted) setLoading(false); } }, [tripId]);
  // The first effect subscribes to the external SSE source and refreshes authoritative state.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); const source = new EventSource(`/api/trips/${tripId}/realtime?scope=plan`); const scheduler = createRealtimeRefreshScheduler(load); const refresh = () => scheduler.schedule(); source.addEventListener("open", refresh); source.addEventListener("message", refresh); source.addEventListener("error", refresh); window.addEventListener("online", refresh); return () => { scheduler.dispose(); source.close(); window.removeEventListener("online", refresh); requestRef.current?.abort(); }; }, [load, tripId]);
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (!data || editing) return; const day = data.days[selectedDay] ?? data.days[0]; setDraft((current) => ({ ...current, dayDate: current.dayDate || day?.date || "", boardNoteId: initialBoardNoteId && data.boardNotes.some((note) => note.id === initialBoardNoteId) ? initialBoardNoteId : current.boardNoteId, pollId: initialPollId && data.polls.some((poll) => poll.id === initialPollId) ? initialPollId : current.pollId })); }, [data, editing, initialBoardNoteId, initialPollId, selectedDay]);
  const selected = data?.days[selectedDay] ?? data?.days[0];
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const input = normalizePlanItemInput(draft); if (!input) { setError("กรอกข้อมูลแผนให้ครบถ้วน"); return; } setBusy(true); try { const url = editing ? `/api/trips/${tripId}/plan/items/${editing.id}` : `/api/trips/${tripId}/plan`; const response = await fetch(url, { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); const body: unknown = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(message((body as { code?: unknown })?.code)); setDraft({ ...empty, dayDate: input.dayDate }); setEditing(null); await load(); } catch (cause) { setError(clientErrorMessage(cause, "บันทึกแผนไม่สำเร็จ")); } finally { setBusy(false); } };
  const mutate = async (url: string, method: string, body?: unknown) => { setBusy(true); try { const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result: unknown = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(message((result as { code?: unknown })?.code)); await load(); } catch (cause) { setError(clientErrorMessage(cause, "ดำเนินการไม่สำเร็จ กรุณาลองใหม่")); } finally { setBusy(false); } };
  const canEdit = !isArchived; const dayOptions = useMemo(() => data?.days ?? [], [data]);
  if (loading && !data) return <div className="plan-state"><CalendarDays size={35}/><p>กำลังโหลดแผน...</p></div>;
  return <section className="plan-workspace"><div className="plan-toolbar"><div><span className="eyebrow">SHARED TRIP PLAN</span><h2>แพลนทริปของเรา</h2><p>เรียงกิจกรรมตามวันและเวลา ทุกคนในทริปช่วยกันเติมได้</p></div>{canEdit && <button className="button button-primary" type="button" onClick={() => { setEditing(null); setDraft({ ...empty, dayDate: selected?.date ?? "" }); }}><Plus size={16}/> เพิ่มรายการ</button>}</div>{isArchived && <p className="plan-archived">ทริปนี้เก็บถาวรแล้ว เปิดดูได้อย่างเดียว</p>}{error && <p className="plan-error" role="alert">{error}</p>}
    {data && <><div className="plan-day-tabs" role="tablist">{data.days.map((day, index) => <button key={day.date} className={index === selectedDay ? "plan-day-tab active" : "plan-day-tab"} type="button" role="tab" aria-label={day.label} onClick={() => setSelectedDay(index)}>{day.label}<small>{day.date}</small></button>)}</div><div className="plan-day-card"><header><div><span className="eyebrow">{selected?.label}</span><h3>{selected?.date}</h3></div><span>{selected?.items.length ?? 0} รายการ</span></header>{selected?.items.length ? <div className="plan-item-list">{selected.items.map((item, index) => <article className="plan-item" data-plan-item-id={item.id} key={item.id}><div className="plan-item-time">{item.startTime ?? "—"}</div><div className="plan-item-content"><h4>{item.title}</h4>{item.description && <p>{item.description}</p>}{item.locationText && <small>📍 {item.locationText}</small>}<div className="plan-item-sources">{item.boardNote && <span>บอร์ด: {item.boardNote.title}</span>}{item.poll && <span>โพล: {item.poll.question}</span>}</div><small>โดย {item.creatorName}</small></div><div className="plan-item-actions">{canEdit && <><button type="button" className="icon-button" aria-label="เลื่อนขึ้น" disabled={busy || index === 0} onClick={() => void mutate(`/api/trips/${tripId}/plan/order`, "POST", { itemId: item.id, direction: "up" })}><ArrowUp size={15}/></button><button type="button" className="icon-button" aria-label="เลื่อนลง" disabled={busy || index === selected.items.length - 1} onClick={() => void mutate(`/api/trips/${tripId}/plan/order`, "POST", { itemId: item.id, direction: "down" })}><ArrowDown size={15}/></button><button type="button" className="icon-button" aria-label="แก้ไข" disabled={busy} onClick={() => { setEditing(item); setDraft({ dayDate: item.dayDate, startTime: item.startTime ?? "", title: item.title, description: item.description, locationText: item.locationText ?? "", boardNoteId: item.boardNote?.id ?? "", pollId: item.poll?.id ?? "" }); }}><Pencil size={15}/></button>{(item.createdBy === currentUserId || ownerId === currentUserId) && <button type="button" className="icon-button danger" aria-label="ลบ" disabled={busy} onClick={() => { if (window.confirm("ลบรายการนี้หรือไม่?")) void mutate(`/api/trips/${tripId}/plan/items/${item.id}`, "DELETE"); }}><Trash2 size={15}/></button>}</>}</div></article>)}</div> : <div className="plan-empty"><span>🧭</span><p>ยังไม่มีรายการในวันนี้</p>{canEdit && <button className="text-button" type="button" onClick={() => { setEditing(null); setDraft({ ...empty, dayDate: selected?.date ?? "" }); }}>เพิ่มรายการแรก</button>}</div>}</div></>}
    {canEdit && <form className="plan-form" onSubmit={submit}><div className="plan-form-heading"><div><span className="eyebrow">{editing ? "EDIT PLAN ITEM" : "ADD TO PLAN"}</span><h3>{editing ? "แก้ไขรายการ" : "เพิ่มกิจกรรม"}</h3></div>{editing && <button className="icon-button" type="button" aria-label="ยกเลิกแก้ไข" onClick={() => { setEditing(null); setDraft({ ...empty, dayDate: selected?.date ?? "" }); }}><X size={16}/></button>}</div><div className="plan-form-grid"><label>วัน<select value={draft.dayDate} onChange={(event) => setDraft({ ...draft, dayDate: event.target.value })}>{dayOptions.map((day) => <option key={day.date} value={day.date}>{day.label} · {day.date}</option>)}</select></label><label>เวลา<input type="time" value={draft.startTime} onChange={(event) => setDraft({ ...draft, startTime: event.target.value })}/></label><label className="plan-form-wide">ชื่อกิจกรรม<input required maxLength={160} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })}/></label><label className="plan-form-wide">รายละเอียด<textarea rows={2} maxLength={1000} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })}/></label><label>สถานที่<input maxLength={200} value={draft.locationText} onChange={(event) => setDraft({ ...draft, locationText: event.target.value })}/></label><label>อ้างอิงบอร์ด<select value={draft.boardNoteId} onChange={(event) => setDraft({ ...draft, boardNoteId: event.target.value })}><option value="">ไม่อ้างอิง</option>{data?.boardNotes.map((note) => <option key={note.id} value={note.id}>{note.title}</option>)}</select></label><label>อ้างอิงโพล<select value={draft.pollId} onChange={(event) => setDraft({ ...draft, pollId: event.target.value })}><option value="">ไม่อ้างอิง</option>{data?.polls.map((poll) => <option key={poll.id} value={poll.id}>{poll.question}</option>)}</select></label></div><button className="button button-primary" type="submit" disabled={busy}>{editing ? "บันทึกการแก้ไข" : "เพิ่มลงแผน"}</button></form>}
  </section>;
}
